package com.ygzc.dao.model;

import java.io.Serializable;

public class Character implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.char_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer charId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.chara
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String chara;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.char_id
     *
     * @return the value of character.char_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getCharId() {
        return charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.char_id
     *
     * @param charId the value for character.char_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCharId(Integer charId) {
        this.charId = charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.chara
     *
     * @return the value of character.chara
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getChara() {
        return chara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.chara
     *
     * @param chara the value for character.chara
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setChara(String chara) {
        this.chara = chara == null ? null : chara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", charId=").append(charId);
        sb.append(", chara=").append(chara);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}