package com.ygzc.dao.model;

import java.io.Serializable;

public class District implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer districtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer nationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.provinces_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer provincesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.district_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table district
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_id
     *
     * @return the value of district.district_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_id
     *
     * @param districtId the value for district.district_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.nation_id
     *
     * @return the value of district.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.nation_id
     *
     * @param nationId the value for district.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.provinces_id
     *
     * @return the value of district.provinces_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getProvincesId() {
        return provincesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.provinces_id
     *
     * @param provincesId the value for district.provinces_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setProvincesId(Integer provincesId) {
        this.provincesId = provincesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.city_id
     *
     * @return the value of district.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.city_id
     *
     * @param cityId the value for district.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_code
     *
     * @return the value of district.district_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_code
     *
     * @param districtCode the value for district.district_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.district_name
     *
     * @return the value of district.district_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.district_name
     *
     * @param districtName the value for district.district_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", districtId=").append(districtId);
        sb.append(", nationId=").append(nationId);
        sb.append(", provincesId=").append(provincesId);
        sb.append(", cityId=").append(cityId);
        sb.append(", districtCode=").append(districtCode);
        sb.append(", districtName=").append(districtName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}