package com.ygzc.dao.model;

import java.io.Serializable;

public class Nation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 地区id  
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer nationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.nation_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 编号
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String nationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.nation_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 国家地区名称
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String nationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nation
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.nation_id
     *
     * @return the value of nation.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.nation_id
     *
     * @param nationId the value for nation.nation_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.nation_code
     *
     * @return the value of nation.nation_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.nation_code
     *
     * @param nationCode the value for nation.nation_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.nation_name
     *
     * @return the value of nation.nation_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.nation_name
     *
     * @param nationName the value for nation.nation_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nationId=").append(nationId);
        sb.append(", nationCode=").append(nationCode);
        sb.append(", nationName=").append(nationName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}