package com.ygzc.dao.model;

import java.io.Serializable;
import java.util.Date;

public class UserProfile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.pid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 用户介绍
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 用户id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.full_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 全名
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.birthday
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.education
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 教育程度
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.vocation
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 职业
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String vocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.longitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 经度
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Float longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.latitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 维度
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Float latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_type
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 份身认证类型
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 身份证号码
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_image_front
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 身份证照片正面 外键
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityImageFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_img_front_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityImgFrontUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_image_back
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 身份证背面 外键
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityImageBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity_img_back_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String identityImgBackUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.check_state
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 审批状态
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer checkState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.introduction
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 个人介绍
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_profile
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.pid
     *
     * @return the value of user_profile.pid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.pid
     *
     * @param pid the value for user_profile.pid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.uid
     *
     * @return the value of user_profile.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.uid
     *
     * @param uid the value for user_profile.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.full_name
     *
     * @return the value of user_profile.full_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.full_name
     *
     * @param fullName the value for user_profile.full_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.birthday
     *
     * @return the value of user_profile.birthday
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.birthday
     *
     * @param birthday the value for user_profile.birthday
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.education
     *
     * @return the value of user_profile.education
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.education
     *
     * @param education the value for user_profile.education
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.vocation
     *
     * @return the value of user_profile.vocation
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.vocation
     *
     * @param vocation the value for user_profile.vocation
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setVocation(String vocation) {
        this.vocation = vocation == null ? null : vocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.longitude
     *
     * @return the value of user_profile.longitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.longitude
     *
     * @param longitude the value for user_profile.longitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.latitude
     *
     * @return the value of user_profile.latitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.latitude
     *
     * @param latitude the value for user_profile.latitude
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_type
     *
     * @return the value of user_profile.identity_type
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_type
     *
     * @param identityType the value for user_profile.identity_type
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType == null ? null : identityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_code
     *
     * @return the value of user_profile.identity_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_code
     *
     * @param identityCode the value for user_profile.identity_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode == null ? null : identityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_image_front
     *
     * @return the value of user_profile.identity_image_front
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityImageFront() {
        return identityImageFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_image_front
     *
     * @param identityImageFront the value for user_profile.identity_image_front
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityImageFront(String identityImageFront) {
        this.identityImageFront = identityImageFront == null ? null : identityImageFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_img_front_url
     *
     * @return the value of user_profile.identity_img_front_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityImgFrontUrl() {
        return identityImgFrontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_img_front_url
     *
     * @param identityImgFrontUrl the value for user_profile.identity_img_front_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityImgFrontUrl(String identityImgFrontUrl) {
        this.identityImgFrontUrl = identityImgFrontUrl == null ? null : identityImgFrontUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_image_back
     *
     * @return the value of user_profile.identity_image_back
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityImageBack() {
        return identityImageBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_image_back
     *
     * @param identityImageBack the value for user_profile.identity_image_back
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityImageBack(String identityImageBack) {
        this.identityImageBack = identityImageBack == null ? null : identityImageBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity_img_back_url
     *
     * @return the value of user_profile.identity_img_back_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdentityImgBackUrl() {
        return identityImgBackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.identity_img_back_url
     *
     * @param identityImgBackUrl the value for user_profile.identity_img_back_url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdentityImgBackUrl(String identityImgBackUrl) {
        this.identityImgBackUrl = identityImgBackUrl == null ? null : identityImgBackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.check_state
     *
     * @return the value of user_profile.check_state
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.check_state
     *
     * @param checkState the value for user_profile.check_state
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCheckState(Integer checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.introduction
     *
     * @return the value of user_profile.introduction
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.introduction
     *
     * @param introduction the value for user_profile.introduction
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.create_date
     *
     * @return the value of user_profile.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.create_date
     *
     * @param createDate the value for user_profile.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.update_date
     *
     * @return the value of user_profile.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.update_date
     *
     * @param updateDate the value for user_profile.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setUpdateDate(Integer updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", uid=").append(uid);
        sb.append(", fullName=").append(fullName);
        sb.append(", birthday=").append(birthday);
        sb.append(", education=").append(education);
        sb.append(", vocation=").append(vocation);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", identityType=").append(identityType);
        sb.append(", identityCode=").append(identityCode);
        sb.append(", identityImageFront=").append(identityImageFront);
        sb.append(", identityImgFrontUrl=").append(identityImgFrontUrl);
        sb.append(", identityImageBack=").append(identityImageBack);
        sb.append(", identityImgBackUrl=").append(identityImgBackUrl);
        sb.append(", checkState=").append(checkState);
        sb.append(", introduction=").append(introduction);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}