package com.ygzc.dao.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 用户id GUID
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 国家代码
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String regionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_num
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 电话号码
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 邮箱
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 性别
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 邀请码
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String idCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 被邀请码
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.point
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 积分
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 昵称
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.device_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.device_ios
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String deviceIos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 头像
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.info
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weibo
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String weibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weixin
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_active
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 否在线
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rands
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 密钥
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private String rands;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.other_flag
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    /**
     * 第三方登陆
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Integer otherFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region_code
     *
     * @return the value of user.region_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region_code
     *
     * @param regionCode the value for user.region_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_num
     *
     * @return the value of user.phone_num
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_num
     *
     * @param phoneNum the value for user.phone_num
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_code
     *
     * @return the value of user.id_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_code
     *
     * @param idCode the value for user.id_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_code
     *
     * @return the value of user.invite_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_code
     *
     * @param inviteCode the value for user.invite_code
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.point
     *
     * @return the value of user.point
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.point
     *
     * @param point the value for user.point
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip
     *
     * @return the value of user.ip
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip
     *
     * @param ip the value for user.ip
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city_id
     *
     * @return the value of user.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city_id
     *
     * @param cityId the value for user.city_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.device_id
     *
     * @return the value of user.device_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.device_id
     *
     * @param deviceId the value for user.device_id
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.device_ios
     *
     * @return the value of user.device_ios
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getDeviceIos() {
        return deviceIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.device_ios
     *
     * @param deviceIos the value for user.device_ios
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setDeviceIos(String deviceIos) {
        this.deviceIos = deviceIos == null ? null : deviceIos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.url
     *
     * @return the value of user.url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.url
     *
     * @param url the value for user.url
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company
     *
     * @return the value of user.company
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company
     *
     * @param company the value for user.company
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.info
     *
     * @return the value of user.info
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.info
     *
     * @param info the value for user.info
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weibo
     *
     * @return the value of user.weibo
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weibo
     *
     * @param weibo the value for user.weibo
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weixin
     *
     * @return the value of user.weixin
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weixin
     *
     * @param weixin the value for user.weixin
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_active
     *
     * @return the value of user.is_active
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_active
     *
     * @param isActive the value for user.is_active
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rands
     *
     * @return the value of user.rands
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public String getRands() {
        return rands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rands
     *
     * @param rands the value for user.rands
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setRands(String rands) {
        this.rands = rands == null ? null : rands.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.other_flag
     *
     * @return the value of user.other_flag
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Integer getOtherFlag() {
        return otherFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.other_flag
     *
     * @param otherFlag the value for user.other_flag
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setOtherFlag(Integer otherFlag) {
        this.otherFlag = otherFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_date
     *
     * @return the value of user.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_date
     *
     * @param createDate the value for user.create_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_date
     *
     * @return the value of user.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_date
     *
     * @param updateDate the value for user.update_date
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", regionCode=").append(regionCode);
        sb.append(", phoneNum=").append(phoneNum);
        sb.append(", email=").append(email);
        sb.append(", gender=").append(gender);
        sb.append(", idCode=").append(idCode);
        sb.append(", inviteCode=").append(inviteCode);
        sb.append(", point=").append(point);
        sb.append(", nickName=").append(nickName);
        sb.append(", ip=").append(ip);
        sb.append(", cityId=").append(cityId);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceIos=").append(deviceIos);
        sb.append(", avatar=").append(avatar);
        sb.append(", password=").append(password);
        sb.append(", url=").append(url);
        sb.append(", company=").append(company);
        sb.append(", location=").append(location);
        sb.append(", info=").append(info);
        sb.append(", weibo=").append(weibo);
        sb.append(", weixin=").append(weixin);
        sb.append(", qq=").append(qq);
        sb.append(", isActive=").append(isActive);
        sb.append(", rands=").append(rands);
        sb.append(", otherFlag=").append(otherFlag);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}