package com.ygzc.dao.mapper.ygzc;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ygzc.dao.model.ygzc.User;
import com.ygzc.dao.model.ygzc.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int insert(User record);

    /**
     * 插入数据
     * 
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * 获取用户信息
     * 
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    User selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jun 06 11:42:26 CST 2018
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据手机号码查询用户信息
     * @param phoneNum
     * @return
     */
    public User getByMobileNumber(String phoneNum);
    
   /**
    * 显示所有用户信息
    * @return
    */
   public List<Map<String, Object>> selectAllUser(Map<String ,Object> map);

   /**
    * 根据phoneNum，password获取登陆用户
	 * @param map
	 * @return
	 */
   public User getLoginUser(Map<String, Object> map);
   
   /**
   *
   * 更新密码
   *
   * @param record
   */
   public void updatePwd(Map<String,Object> params);
   
   /**
    * 根据手机删除用户信息
	 * @param phoneNum
	 * @return
	 */
   public int deleteByPhoneNum(String phoneNum);
    
}